### ISSUE TITLE
README file missing

### ISSUE THREAD

**Issue by kuusas** [UsergroupsLT/ugcal#1]
What's that and how it works?

**Comment by Pawka** [comment]
It doesn't.

**Comment by kuusas** [comment]
Yes it does! :) <img width="1021" alt="screenshot 2016-03-14 21 10 27" src="https://cloud.githubusercontent.com/assets/1662530/13756637/7b1d4996-ea29-11e5-999e-fc5322e8fc8c.png">

**Comment by Pawka** [comment]
It doesn't work.

**Comment by Pawka** [comment]
Added `README.md` for ya :-)
